// Assignment

//Q-1
// alert("Welcome to my website!");

//Q-2
// alert("JavaScript Alert\n\n Error! Please enter a valid password.");

//Q-3
// alert("JavaScript Alert\n\nWelcome to JS Land...\nHappy coding!");

//Q-4
// alert("JavaScript Alert\n\n Welcome to JS Land...");
// alert("Happy coding!\n Prevent this page is creating for addition dialogs");

//Q-5
  // alert("JavaScript Alert\n\n Hello...I can run Js through my web browser's console");